### To create a new patient record
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "John Kafka Test2",
  "email": "test@gamil.com",
  "address": "123 main street22",
  "dateOfBirth": "1995-09-09",
  "registeredDate": "2024-11-28"
}



###