### To create a new patient record
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "jhon doe kafka final_test",
  "email": "jhonedoekafkafinal_test@gamil.com",
  "address": "123 main reet22",
  "dateOfBirth": "1995-10-09",
  "registeredDate": "2025-11-28"
}



###